### ISSUE TITLE
bug with python 3.5

### ISSUE THREAD

**Issue by sdementen** [blue-yonder/sqla_toolkit#1]
I think the __init__.py should use relative imports in python 3 like

```
__version__ = '0.1'
from . import search

```
but I wonder if it would not be better to flatten the structure of the project to one level (ie move the filers in search on folder up).

**Comment by kopf** [comment]
Hey @sdementen, thanks for the bug report. Unfortunately, restrictions in the way flask-toolkit does things made it unsuitable for what we were trying to do in-house, and we've instead thrown together a small module to achieve what we needed (essentially something like django-url-filter but without django as a requirement). 

This will probably be released soon as an open source project, so I'll try to remember to ping you here to point you to it. 

Just out of interest, how did you come across this project?

**Comment by sdementen** [comment]
OK.
I found the project by
1) looking for a solution to filter/search a SA collection (for an API project)
2) found flask-restless and their code for filtering/searching
3) wondered if it was taken from a standalone package
4) search on Google the first line of the __init__ file "Provides search queries for SQLAlchemy models" and found your repo
Exactly what I needed!

Could you tell me a bit more on your new project ?  Will it support SA ?

**Comment by kopf** [comment]
The new library is significantly smaller and simpler. It's built for SQLAlchemy - primarily for the SQLA Expression Language, to maximise efficiency. This is in contrast to flask-restless, which uses the ORM. 

The API looks something like:

```
def query(selectable, filters, limit=None, offset=None, order=None, asc=True):
    ...
    return selectable
```

So, you pass in an SQLAlchemy selectable object, some filters (e.g. `id__lt=4`), a limit/offset/order for pagination, and you get back this selectable with the filters having been applied. The selectable is then yours to do with what you please. 

If that's something that you might find useful, then either myself or @hoffmann can ping you here once it's being open sourced!

**Comment by sdementen** [comment]
yes definitely interested !

I also wanted to be able to write filters in a more pythonic way. So
instead of writing expressions like id__lt=4 or [{"name": "id", "op": "lt",
"val": 4}], to be able to write "id<4". Final objective is to be able to
write for an API
https//api.myserver.com/v1/users?filters=id<4 and
address.country="france"&otherkindofparameters=somevalues
I find it more readable than the equivalent:
[{"name": "id", "op": "lt", "val": 4}]

**Comment by kopf** [comment]
@sdementen here you go, have a look at https://github.com/blue-yonder/qsqla

**Comment by sdementen** [comment]
hello @kopf , I had a look at the qsqla project but what I wanted is a syntax akin to:
create_filter("Customer.id>123 and Customer.name.startswith('foo')", ) => generate the sql filters

I finally cooked something with the ast module to transform "A and B" tosqla "and_(A, B)" (ditto for or and not) + to control the ast tree for unsafe nodes and then a call to eval on this cleaned/transformed code.
